/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OpensourceRouteImport } from './routes/opensource'
import { Route as RapidtransitRouteImport } from './routes/rapidtransit'
import { Route as SlowzonesRouteImport } from './routes/slowzones'
import { Route as LineIndexRouteImport } from './routes/$line/index'
import { Route as LineDelaysRouteImport } from './routes/$line/delays'
import { Route as LineFleetRouteImport } from './routes/$line/fleet'
import { Route as LineLeaderboardRouteImport } from './routes/$line/leaderboard'
import { Route as LinePredictionsRouteImport } from './routes/$line/predictions'
import { Route as LineReliabilityRouteImport } from './routes/$line/reliability'
import { Route as LineRidershipRouteImport } from './routes/$line/ridership'
import { Route as LineServiceRouteImport } from './routes/$line/service'
import { Route as LineSlowzonesRouteImport } from './routes/$line/slowzones'
import { Route as LineSpeedRouteImport } from './routes/$line/speed'
import { Route as LineSpeedmapRouteImport } from './routes/$line/speedmap'
import { Route as SystemIndexRouteImport } from './routes/system/index'
import { Route as SystemRidershipRouteImport } from './routes/system/ridership'
import { Route as SystemSlowzonesRouteImport } from './routes/system/slowzones'
import { Route as LineTripsMultiIndexRouteImport } from './routes/$line/trips/multi/index'
import { Route as LineTripsSingleIndexRouteImport } from './routes/$line/trips/single/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OpensourceRoute = OpensourceRouteImport.update({
  id: '/opensource',
  path: '/opensource',
  getParentRoute: () => rootRouteImport,
} as any)
const RapidtransitRoute = RapidtransitRouteImport.update({
  id: '/rapidtransit',
  path: '/rapidtransit',
  getParentRoute: () => rootRouteImport,
} as any)
const SlowzonesRoute = SlowzonesRouteImport.update({
  id: '/slowzones',
  path: '/slowzones',
  getParentRoute: () => rootRouteImport,
} as any)
const LineIndexRoute = LineIndexRouteImport.update({
  id: '/$line/',
  path: '/$line/',
  getParentRoute: () => rootRouteImport,
} as any)
const LineDelaysRoute = LineDelaysRouteImport.update({
  id: '/$line/delays',
  path: '/$line/delays',
  getParentRoute: () => rootRouteImport,
} as any)
const LineFleetRoute = LineFleetRouteImport.update({
  id: '/$line/fleet',
  path: '/$line/fleet',
  getParentRoute: () => rootRouteImport,
} as any)
const LineLeaderboardRoute = LineLeaderboardRouteImport.update({
  id: '/$line/leaderboard',
  path: '/$line/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LinePredictionsRoute = LinePredictionsRouteImport.update({
  id: '/$line/predictions',
  path: '/$line/predictions',
  getParentRoute: () => rootRouteImport,
} as any)
const LineReliabilityRoute = LineReliabilityRouteImport.update({
  id: '/$line/reliability',
  path: '/$line/reliability',
  getParentRoute: () => rootRouteImport,
} as any)
const LineRidershipRoute = LineRidershipRouteImport.update({
  id: '/$line/ridership',
  path: '/$line/ridership',
  getParentRoute: () => rootRouteImport,
} as any)
const LineServiceRoute = LineServiceRouteImport.update({
  id: '/$line/service',
  path: '/$line/service',
  getParentRoute: () => rootRouteImport,
} as any)
const LineSlowzonesRoute = LineSlowzonesRouteImport.update({
  id: '/$line/slowzones',
  path: '/$line/slowzones',
  getParentRoute: () => rootRouteImport,
} as any)
const LineSpeedRoute = LineSpeedRouteImport.update({
  id: '/$line/speed',
  path: '/$line/speed',
  getParentRoute: () => rootRouteImport,
} as any)
const LineSpeedmapRoute = LineSpeedmapRouteImport.update({
  id: '/$line/speedmap',
  path: '/$line/speedmap',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemIndexRoute = SystemIndexRouteImport.update({
  id: '/system/',
  path: '/system/',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemRidershipRoute = SystemRidershipRouteImport.update({
  id: '/system/ridership',
  path: '/system/ridership',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemSlowzonesRoute = SystemSlowzonesRouteImport.update({
  id: '/system/slowzones',
  path: '/system/slowzones',
  getParentRoute: () => rootRouteImport,
} as any)
const LineTripsMultiIndexRoute = LineTripsMultiIndexRouteImport.update({
  id: '/$line/trips/multi/',
  path: '/$line/trips/multi/',
  getParentRoute: () => rootRouteImport,
} as any)
const LineTripsSingleIndexRoute = LineTripsSingleIndexRouteImport.update({
  id: '/$line/trips/single/',
  path: '/$line/trips/single/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/opensource': typeof OpensourceRoute
  '/rapidtransit': typeof RapidtransitRoute
  '/slowzones': typeof SlowzonesRoute
  '/$line/delays': typeof LineDelaysRoute
  '/$line/fleet': typeof LineFleetRoute
  '/$line/leaderboard': typeof LineLeaderboardRoute
  '/$line/predictions': typeof LinePredictionsRoute
  '/$line/reliability': typeof LineReliabilityRoute
  '/$line/ridership': typeof LineRidershipRoute
  '/$line/service': typeof LineServiceRoute
  '/$line/slowzones': typeof LineSlowzonesRoute
  '/$line/speed': typeof LineSpeedRoute
  '/$line/speedmap': typeof LineSpeedmapRoute
  '/system/ridership': typeof SystemRidershipRoute
  '/system/slowzones': typeof SystemSlowzonesRoute
  '/$line/': typeof LineIndexRoute
  '/system/': typeof SystemIndexRoute
  '/$line/trips/multi/': typeof LineTripsMultiIndexRoute
  '/$line/trips/single/': typeof LineTripsSingleIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/opensource': typeof OpensourceRoute
  '/rapidtransit': typeof RapidtransitRoute
  '/slowzones': typeof SlowzonesRoute
  '/$line/delays': typeof LineDelaysRoute
  '/$line/fleet': typeof LineFleetRoute
  '/$line/leaderboard': typeof LineLeaderboardRoute
  '/$line/predictions': typeof LinePredictionsRoute
  '/$line/reliability': typeof LineReliabilityRoute
  '/$line/ridership': typeof LineRidershipRoute
  '/$line/service': typeof LineServiceRoute
  '/$line/slowzones': typeof LineSlowzonesRoute
  '/$line/speed': typeof LineSpeedRoute
  '/$line/speedmap': typeof LineSpeedmapRoute
  '/system/ridership': typeof SystemRidershipRoute
  '/system/slowzones': typeof SystemSlowzonesRoute
  '/$line': typeof LineIndexRoute
  '/system': typeof SystemIndexRoute
  '/$line/trips/multi': typeof LineTripsMultiIndexRoute
  '/$line/trips/single': typeof LineTripsSingleIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/opensource': typeof OpensourceRoute
  '/rapidtransit': typeof RapidtransitRoute
  '/slowzones': typeof SlowzonesRoute
  '/$line/delays': typeof LineDelaysRoute
  '/$line/fleet': typeof LineFleetRoute
  '/$line/leaderboard': typeof LineLeaderboardRoute
  '/$line/predictions': typeof LinePredictionsRoute
  '/$line/reliability': typeof LineReliabilityRoute
  '/$line/ridership': typeof LineRidershipRoute
  '/$line/service': typeof LineServiceRoute
  '/$line/slowzones': typeof LineSlowzonesRoute
  '/$line/speed': typeof LineSpeedRoute
  '/$line/speedmap': typeof LineSpeedmapRoute
  '/system/ridership': typeof SystemRidershipRoute
  '/system/slowzones': typeof SystemSlowzonesRoute
  '/$line/': typeof LineIndexRoute
  '/system/': typeof SystemIndexRoute
  '/$line/trips/multi/': typeof LineTripsMultiIndexRoute
  '/$line/trips/single/': typeof LineTripsSingleIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/opensource'
    | '/rapidtransit'
    | '/slowzones'
    | '/$line/delays'
    | '/$line/fleet'
    | '/$line/leaderboard'
    | '/$line/predictions'
    | '/$line/reliability'
    | '/$line/ridership'
    | '/$line/service'
    | '/$line/slowzones'
    | '/$line/speed'
    | '/$line/speedmap'
    | '/system/ridership'
    | '/system/slowzones'
    | '/$line/'
    | '/system/'
    | '/$line/trips/multi/'
    | '/$line/trips/single/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/opensource'
    | '/rapidtransit'
    | '/slowzones'
    | '/$line/delays'
    | '/$line/fleet'
    | '/$line/leaderboard'
    | '/$line/predictions'
    | '/$line/reliability'
    | '/$line/ridership'
    | '/$line/service'
    | '/$line/slowzones'
    | '/$line/speed'
    | '/$line/speedmap'
    | '/system/ridership'
    | '/system/slowzones'
    | '/$line'
    | '/system'
    | '/$line/trips/multi'
    | '/$line/trips/single'
  id:
    | '__root__'
    | '/'
    | '/opensource'
    | '/rapidtransit'
    | '/slowzones'
    | '/$line/delays'
    | '/$line/fleet'
    | '/$line/leaderboard'
    | '/$line/predictions'
    | '/$line/reliability'
    | '/$line/ridership'
    | '/$line/service'
    | '/$line/slowzones'
    | '/$line/speed'
    | '/$line/speedmap'
    | '/system/ridership'
    | '/system/slowzones'
    | '/$line/'
    | '/system/'
    | '/$line/trips/multi/'
    | '/$line/trips/single/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OpensourceRoute: typeof OpensourceRoute
  RapidtransitRoute: typeof RapidtransitRoute
  SlowzonesRoute: typeof SlowzonesRoute
  LineDelaysRoute: typeof LineDelaysRoute
  LineFleetRoute: typeof LineFleetRoute
  LineLeaderboardRoute: typeof LineLeaderboardRoute
  LinePredictionsRoute: typeof LinePredictionsRoute
  LineReliabilityRoute: typeof LineReliabilityRoute
  LineRidershipRoute: typeof LineRidershipRoute
  LineServiceRoute: typeof LineServiceRoute
  LineSlowzonesRoute: typeof LineSlowzonesRoute
  LineSpeedRoute: typeof LineSpeedRoute
  LineSpeedmapRoute: typeof LineSpeedmapRoute
  SystemRidershipRoute: typeof SystemRidershipRoute
  SystemSlowzonesRoute: typeof SystemSlowzonesRoute
  LineIndexRoute: typeof LineIndexRoute
  SystemIndexRoute: typeof SystemIndexRoute
  LineTripsMultiIndexRoute: typeof LineTripsMultiIndexRoute
  LineTripsSingleIndexRoute: typeof LineTripsSingleIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opensource': {
      id: '/opensource'
      path: '/opensource'
      fullPath: '/opensource'
      preLoaderRoute: typeof OpensourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rapidtransit': {
      id: '/rapidtransit'
      path: '/rapidtransit'
      fullPath: '/rapidtransit'
      preLoaderRoute: typeof RapidtransitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/slowzones': {
      id: '/slowzones'
      path: '/slowzones'
      fullPath: '/slowzones'
      preLoaderRoute: typeof SlowzonesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$line/': {
      id: '/$line/'
      path: '/$line'
      fullPath: '/$line/'
      preLoaderRoute: typeof LineIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$line/delays': {
      id: '/$line/delays'
      path: '/$line/delays'
      fullPath: '/$line/delays'
      preLoaderRoute: typeof LineDelaysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$line/fleet': {
      id: '/$line/fleet'
      path: '/$line/fleet'
      fullPath: '/$line/fleet'
      preLoaderRoute: typeof LineFleetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$line/leaderboard': {
      id: '/$line/leaderboard'
      path: '/$line/leaderboard'
      fullPath: '/$line/leaderboard'
      preLoaderRoute: typeof LineLeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$line/predictions': {
      id: '/$line/predictions'
      path: '/$line/predictions'
      fullPath: '/$line/predictions'
      preLoaderRoute: typeof LinePredictionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$line/reliability': {
      id: '/$line/reliability'
      path: '/$line/reliability'
      fullPath: '/$line/reliability'
      preLoaderRoute: typeof LineReliabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$line/ridership': {
      id: '/$line/ridership'
      path: '/$line/ridership'
      fullPath: '/$line/ridership'
      preLoaderRoute: typeof LineRidershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$line/service': {
      id: '/$line/service'
      path: '/$line/service'
      fullPath: '/$line/service'
      preLoaderRoute: typeof LineServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$line/slowzones': {
      id: '/$line/slowzones'
      path: '/$line/slowzones'
      fullPath: '/$line/slowzones'
      preLoaderRoute: typeof LineSlowzonesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$line/speed': {
      id: '/$line/speed'
      path: '/$line/speed'
      fullPath: '/$line/speed'
      preLoaderRoute: typeof LineSpeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$line/speedmap': {
      id: '/$line/speedmap'
      path: '/$line/speedmap'
      fullPath: '/$line/speedmap'
      preLoaderRoute: typeof LineSpeedmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system/': {
      id: '/system/'
      path: '/system'
      fullPath: '/system/'
      preLoaderRoute: typeof SystemIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system/ridership': {
      id: '/system/ridership'
      path: '/system/ridership'
      fullPath: '/system/ridership'
      preLoaderRoute: typeof SystemRidershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system/slowzones': {
      id: '/system/slowzones'
      path: '/system/slowzones'
      fullPath: '/system/slowzones'
      preLoaderRoute: typeof SystemSlowzonesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$line/trips/multi/': {
      id: '/$line/trips/multi/'
      path: '/$line/trips/multi'
      fullPath: '/$line/trips/multi/'
      preLoaderRoute: typeof LineTripsMultiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$line/trips/single/': {
      id: '/$line/trips/single/'
      path: '/$line/trips/single'
      fullPath: '/$line/trips/single/'
      preLoaderRoute: typeof LineTripsSingleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OpensourceRoute: OpensourceRoute,
  RapidtransitRoute: RapidtransitRoute,
  SlowzonesRoute: SlowzonesRoute,
  LineDelaysRoute: LineDelaysRoute,
  LineFleetRoute: LineFleetRoute,
  LineLeaderboardRoute: LineLeaderboardRoute,
  LinePredictionsRoute: LinePredictionsRoute,
  LineReliabilityRoute: LineReliabilityRoute,
  LineRidershipRoute: LineRidershipRoute,
  LineServiceRoute: LineServiceRoute,
  LineSlowzonesRoute: LineSlowzonesRoute,
  LineSpeedRoute: LineSpeedRoute,
  LineSpeedmapRoute: LineSpeedmapRoute,
  SystemRidershipRoute: SystemRidershipRoute,
  SystemSlowzonesRoute: SystemSlowzonesRoute,
  LineIndexRoute: LineIndexRoute,
  SystemIndexRoute: SystemIndexRoute,
  LineTripsMultiIndexRoute: LineTripsMultiIndexRoute,
  LineTripsSingleIndexRoute: LineTripsSingleIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
