import type { SpeedPairData } from './segment';

export const TEST_DATA: SpeedPairData[] = [
  {
    service_date: '2025-02-24',
    travel_time: 16.0,
    route: 'Blue',
    from_id: 'place-bomnl',
    to_id: 'place-gover',
  },
  {
    service_date: '2025-02-25',
    travel_time: 16.0,
    route: 'Blue',
    from_id: 'place-bomnl',
    to_id: 'place-gover',
  },
  {
    service_date: '2025-02-24',
    travel_time: 36.0,
    route: 'Blue',
    from_id: 'place-gover',
    to_id: 'place-bomnl',
  },
  {
    service_date: '2025-02-25',
    travel_time: 37.0,
    route: 'Blue',
    from_id: 'place-gover',
    to_id: 'place-bomnl',
  },
  {
    service_date: '2025-02-24',
    travel_time: 34.0,
    route: 'Blue',
    from_id: 'place-gover',
    to_id: 'place-state',
  },
  {
    service_date: '2025-02-25',
    travel_time: 34.0,
    route: 'Blue',
    from_id: 'place-gover',
    to_id: 'place-state',
  },
  {
    service_date: '2025-02-24',
    travel_time: 34.0,
    route: 'Blue',
    from_id: 'place-state',
    to_id: 'place-gover',
  },
  {
    service_date: '2025-02-25',
    travel_time: 35.0,
    route: 'Blue',
    from_id: 'place-state',
    to_id: 'place-gover',
  },
  {
    service_date: '2025-02-24',
    travel_time: 30.0,
    route: 'Blue',
    from_id: 'place-state',
    to_id: 'place-aqucl',
  },
  {
    service_date: '2025-02-25',
    travel_time: 31.0,
    route: 'Blue',
    from_id: 'place-state',
    to_id: 'place-aqucl',
  },
  {
    service_date: '2025-02-24',
    travel_time: 29.0,
    route: 'Blue',
    from_id: 'place-aqucl',
    to_id: 'place-state',
  },
  {
    service_date: '2025-02-25',
    travel_time: 30.0,
    route: 'Blue',
    from_id: 'place-aqucl',
    to_id: 'place-state',
  },
  {
    service_date: '2025-02-24',
    travel_time: 109.0,
    route: 'Blue',
    from_id: 'place-aqucl',
    to_id: 'place-mvbcl',
  },
  {
    service_date: '2025-02-25',
    travel_time: 109.0,
    route: 'Blue',
    from_id: 'place-aqucl',
    to_id: 'place-mvbcl',
  },
  {
    service_date: '2025-02-24',
    travel_time: 90.0,
    route: 'Blue',
    from_id: 'place-mvbcl',
    to_id: 'place-aqucl',
  },
  {
    service_date: '2025-02-25',
    travel_time: 90.0,
    route: 'Blue',
    from_id: 'place-mvbcl',
    to_id: 'place-aqucl',
  },
  {
    service_date: '2025-02-24',
    travel_time: 81.0,
    route: 'Blue',
    from_id: 'place-mvbcl',
    to_id: 'place-aport',
  },
  {
    service_date: '2025-02-25',
    travel_time: 81.0,
    route: 'Blue',
    from_id: 'place-mvbcl',
    to_id: 'place-aport',
  },
  {
    service_date: '2025-02-24',
    travel_time: 98.0,
    route: 'Blue',
    from_id: 'place-aport',
    to_id: 'place-mvbcl',
  },
  {
    service_date: '2025-02-25',
    travel_time: 99.0,
    route: 'Blue',
    from_id: 'place-aport',
    to_id: 'place-mvbcl',
  },
  {
    service_date: '2025-02-24',
    travel_time: 59.0,
    route: 'Blue',
    from_id: 'place-aport',
    to_id: 'place-wimnl',
  },
  {
    service_date: '2025-02-25',
    travel_time: 59.0,
    route: 'Blue',
    from_id: 'place-aport',
    to_id: 'place-wimnl',
  },
  {
    service_date: '2025-02-24',
    travel_time: 56.5,
    route: 'Blue',
    from_id: 'place-wimnl',
    to_id: 'place-aport',
  },
  {
    service_date: '2025-02-25',
    travel_time: 56.0,
    route: 'Blue',
    from_id: 'place-wimnl',
    to_id: 'place-aport',
  },
  {
    service_date: '2025-02-24',
    travel_time: 108.0,
    route: 'Blue',
    from_id: 'place-wimnl',
    to_id: 'place-orhte',
  },
  {
    service_date: '2025-02-25',
    travel_time: 108.0,
    route: 'Blue',
    from_id: 'place-wimnl',
    to_id: 'place-orhte',
  },
  {
    service_date: '2025-02-24',
    travel_time: 104.0,
    route: 'Blue',
    from_id: 'place-orhte',
    to_id: 'place-wimnl',
  },
  {
    service_date: '2025-02-25',
    travel_time: 105.0,
    route: 'Blue',
    from_id: 'place-orhte',
    to_id: 'place-wimnl',
  },
  {
    service_date: '2025-02-24',
    travel_time: 58.0,
    route: 'Blue',
    from_id: 'place-orhte',
    to_id: 'place-sdmnl',
  },
  {
    service_date: '2025-02-25',
    travel_time: 58.0,
    route: 'Blue',
    from_id: 'place-orhte',
    to_id: 'place-sdmnl',
  },
  {
    service_date: '2025-02-24',
    travel_time: 61.0,
    route: 'Blue',
    from_id: 'place-sdmnl',
    to_id: 'place-orhte',
  },
  {
    service_date: '2025-02-25',
    travel_time: 61.0,
    route: 'Blue',
    from_id: 'place-sdmnl',
    to_id: 'place-orhte',
  },
  {
    service_date: '2025-02-24',
    travel_time: 47.0,
    route: 'Blue',
    from_id: 'place-sdmnl',
    to_id: 'place-bmmnl',
  },
  {
    service_date: '2025-02-25',
    travel_time: 47.0,
    route: 'Blue',
    from_id: 'place-sdmnl',
    to_id: 'place-bmmnl',
  },
  {
    service_date: '2025-02-24',
    travel_time: 46.0,
    route: 'Blue',
    from_id: 'place-bmmnl',
    to_id: 'place-sdmnl',
  },
  {
    service_date: '2025-02-25',
    travel_time: 46.5,
    route: 'Blue',
    from_id: 'place-bmmnl',
    to_id: 'place-sdmnl',
  },
  {
    service_date: '2025-02-24',
    travel_time: 73.5,
    route: 'Blue',
    from_id: 'place-bmmnl',
    to_id: 'place-rbmnl',
  },
  {
    service_date: '2025-02-25',
    travel_time: 74.0,
    route: 'Blue',
    from_id: 'place-bmmnl',
    to_id: 'place-rbmnl',
  },
  {
    service_date: '2025-02-24',
    travel_time: 69.0,
    route: 'Blue',
    from_id: 'place-rbmnl',
    to_id: 'place-bmmnl',
  },
  {
    service_date: '2025-02-25',
    travel_time: 70.0,
    route: 'Blue',
    from_id: 'place-rbmnl',
    to_id: 'place-bmmnl',
  },
  {
    service_date: '2025-02-24',
    travel_time: 78.5,
    route: 'Blue',
    from_id: 'place-rbmnl',
    to_id: 'place-wondl',
  },
  {
    service_date: '2025-02-25',
    travel_time: 75.0,
    route: 'Blue',
    from_id: 'place-rbmnl',
    to_id: 'place-wondl',
  },
  {
    service_date: '2025-02-24',
    travel_time: 35.0,
    route: 'Blue',
    from_id: 'place-wondl',
    to_id: 'place-rbmnl',
  },
  {
    service_date: '2025-02-25',
    travel_time: 35.0,
    route: 'Blue',
    from_id: 'place-wondl',
    to_id: 'place-rbmnl',
  },
  {
    service_date: '2025-02-24',
    travel_time: 117.5,
    route: 'Green',
    from_id: 'place-kencl',
    to_id: 'place-hymnl',
  },
  {
    service_date: '2025-02-25',
    travel_time: 120.0,
    route: 'Green',
    from_id: 'place-kencl',
    to_id: 'place-hymnl',
  },
  {
    service_date: '2025-02-24',
    travel_time: 142.0,
    route: 'Green',
    from_id: 'place-kencl',
    to_id: 'place-fenwy',
  },
  {
    service_date: '2025-02-25',
    travel_time: 143.0,
    route: 'Green',
    from_id: 'place-kencl',
    to_id: 'place-fenwy',
  },
  {
    service_date: '2025-02-24',
    travel_time: 109.0,
    route: 'Green',
    from_id: 'place-hymnl',
    to_id: 'place-coecl',
  },
  {
    service_date: '2025-02-25',
    travel_time: 107.0,
    route: 'Green',
    from_id: 'place-hymnl',
    to_id: 'place-coecl',
  },
  {
    service_date: '2025-02-24',
    travel_time: 117.0,
    route: 'Green',
    from_id: 'place-hymnl',
    to_id: 'place-kencl',
  },
  {
    service_date: '2025-02-25',
    travel_time: 116.0,
    route: 'Green',
    from_id: 'place-hymnl',
    to_id: 'place-kencl',
  },
  {
    service_date: '2025-02-24',
    travel_time: 66.0,
    route: 'Green',
    from_id: 'place-coecl',
    to_id: 'place-armnl',
  },
  {
    service_date: '2025-02-25',
    travel_time: 67.0,
    route: 'Green',
    from_id: 'place-coecl',
    to_id: 'place-armnl',
  },
  {
    service_date: '2025-02-24',
    travel_time: 100.5,
    route: 'Green',
    from_id: 'place-coecl',
    to_id: 'place-hymnl',
  },
  {
    service_date: '2025-02-25',
    travel_time: 99.0,
    route: 'Green',
    from_id: 'place-coecl',
    to_id: 'place-hymnl',
  },
  {
    service_date: '2025-02-24',
    travel_time: 118.0,
    route: 'Green',
    from_id: 'place-armnl',
    to_id: 'place-boyls',
  },
  {
    service_date: '2025-02-25',
    travel_time: 120.0,
    route: 'Green',
    from_id: 'place-armnl',
    to_id: 'place-boyls',
  },
  {
    service_date: '2025-02-24',
    travel_time: 67.0,
    route: 'Green',
    from_id: 'place-armnl',
    to_id: 'place-coecl',
  },
  {
    service_date: '2025-02-25',
    travel_time: 60.0,
    route: 'Green',
    from_id: 'place-armnl',
    to_id: 'place-coecl',
  },
  {
    service_date: '2025-02-24',
    travel_time: 66.0,
    route: 'Green',
    from_id: 'place-boyls',
    to_id: 'place-pktrm',
  },
  {
    service_date: '2025-02-25',
    travel_time: 67.0,
    route: 'Green',
    from_id: 'place-boyls',
    to_id: 'place-pktrm',
  },
  {
    service_date: '2025-02-24',
    travel_time: 111.0,
    route: 'Green',
    from_id: 'place-boyls',
    to_id: 'place-armnl',
  },
  {
    service_date: '2025-02-25',
    travel_time: 107.0,
    route: 'Green',
    from_id: 'place-boyls',
    to_id: 'place-armnl',
  },
  {
    service_date: '2025-02-24',
    travel_time: 66.0,
    route: 'Green',
    from_id: 'place-river',
    to_id: 'place-woodl',
  },
  {
    service_date: '2025-02-25',
    travel_time: 63.0,
    route: 'Green',
    from_id: 'place-river',
    to_id: 'place-woodl',
  },
  {
    service_date: '2025-02-24',
    travel_time: 93.0,
    route: 'Green',
    from_id: 'place-woodl',
    to_id: 'place-waban',
  },
  {
    service_date: '2025-02-25',
    travel_time: 91.0,
    route: 'Green',
    from_id: 'place-woodl',
    to_id: 'place-waban',
  },
  {
    service_date: '2025-02-24',
    travel_time: 96.0,
    route: 'Green',
    from_id: 'place-woodl',
    to_id: 'place-river',
  },
  {
    service_date: '2025-02-25',
    travel_time: 96.0,
    route: 'Green',
    from_id: 'place-woodl',
    to_id: 'place-river',
  },
  {
    service_date: '2025-02-24',
    travel_time: 85.0,
    route: 'Green',
    from_id: 'place-waban',
    to_id: 'place-eliot',
  },
  {
    service_date: '2025-02-25',
    travel_time: 84.0,
    route: 'Green',
    from_id: 'place-waban',
    to_id: 'place-eliot',
  },
  {
    service_date: '2025-02-24',
    travel_time: 90.0,
    route: 'Green',
    from_id: 'place-waban',
    to_id: 'place-woodl',
  },
  {
    service_date: '2025-02-25',
    travel_time: 89.0,
    route: 'Green',
    from_id: 'place-waban',
    to_id: 'place-woodl',
  },
  {
    service_date: '2025-02-24',
    travel_time: 96.0,
    route: 'Green',
    from_id: 'place-eliot',
    to_id: 'place-newtn',
  },
  {
    service_date: '2025-02-25',
    travel_time: 94.0,
    route: 'Green',
    from_id: 'place-eliot',
    to_id: 'place-newtn',
  },
  {
    service_date: '2025-02-24',
    travel_time: 84.0,
    route: 'Green',
    from_id: 'place-eliot',
    to_id: 'place-waban',
  },
  {
    service_date: '2025-02-25',
    travel_time: 82.0,
    route: 'Green',
    from_id: 'place-eliot',
    to_id: 'place-waban',
  },
  {
    service_date: '2025-02-24',
    travel_time: 86.0,
    route: 'Green',
    from_id: 'place-newtn',
    to_id: 'place-newto',
  },
  {
    service_date: '2025-02-25',
    travel_time: 84.0,
    route: 'Green',
    from_id: 'place-newtn',
    to_id: 'place-newto',
  },
  {
    service_date: '2025-02-24',
    travel_time: 91.0,
    route: 'Green',
    from_id: 'place-newtn',
    to_id: 'place-eliot',
  },
  {
    service_date: '2025-02-25',
    travel_time: 90.0,
    route: 'Green',
    from_id: 'place-newtn',
    to_id: 'place-eliot',
  },
  {
    service_date: '2025-02-24',
    travel_time: 168.0,
    route: 'Green',
    from_id: 'place-newto',
    to_id: 'place-chhil',
  },
  {
    service_date: '2025-02-25',
    travel_time: 164.0,
    route: 'Green',
    from_id: 'place-newto',
    to_id: 'place-chhil',
  },
  {
    service_date: '2025-02-24',
    travel_time: 89.0,
    route: 'Green',
    from_id: 'place-newto',
    to_id: 'place-newtn',
  },
  {
    service_date: '2025-02-25',
    travel_time: 87.0,
    route: 'Green',
    from_id: 'place-newto',
    to_id: 'place-newtn',
  },
  {
    service_date: '2025-02-24',
    travel_time: 126.0,
    route: 'Green',
    from_id: 'place-chhil',
    to_id: 'place-rsmnl',
  },
  {
    service_date: '2025-02-25',
    travel_time: 120.0,
    route: 'Green',
    from_id: 'place-chhil',
    to_id: 'place-rsmnl',
  },
  {
    service_date: '2025-02-24',
    travel_time: 166.0,
    route: 'Green',
    from_id: 'place-chhil',
    to_id: 'place-newto',
  },
  {
    service_date: '2025-02-25',
    travel_time: 164.0,
    route: 'Green',
    from_id: 'place-chhil',
    to_id: 'place-newto',
  },
  {
    service_date: '2025-02-24',
    travel_time: 120.0,
    route: 'Green',
    from_id: 'place-rsmnl',
    to_id: 'place-bcnfd',
  },
  {
    service_date: '2025-02-25',
    travel_time: 120.0,
    route: 'Green',
    from_id: 'place-rsmnl',
    to_id: 'place-bcnfd',
  },
  {
    service_date: '2025-02-24',
    travel_time: 126.0,
    route: 'Green',
    from_id: 'place-rsmnl',
    to_id: 'place-chhil',
  },
  {
    service_date: '2025-02-25',
    travel_time: 120.0,
    route: 'Green',
    from_id: 'place-rsmnl',
    to_id: 'place-chhil',
  },
  {
    service_date: '2025-02-24',
    travel_time: 102.0,
    route: 'Green',
    from_id: 'place-bcnfd',
    to_id: 'place-brkhl',
  },
  {
    service_date: '2025-02-25',
    travel_time: 102.0,
    route: 'Green',
    from_id: 'place-bcnfd',
    to_id: 'place-brkhl',
  },
  {
    service_date: '2025-02-24',
    travel_time: 131.0,
    route: 'Green',
    from_id: 'place-bcnfd',
    to_id: 'place-rsmnl',
  },
  {
    service_date: '2025-02-25',
    travel_time: 126.0,
    route: 'Green',
    from_id: 'place-bcnfd',
    to_id: 'place-rsmnl',
  },
  {
    service_date: '2025-02-24',
    travel_time: 68.0,
    route: 'Green',
    from_id: 'place-brkhl',
    to_id: 'place-bvmnl',
  },
  {
    service_date: '2025-02-25',
    travel_time: 68.0,
    route: 'Green',
    from_id: 'place-brkhl',
    to_id: 'place-bvmnl',
  },
  {
    service_date: '2025-02-24',
    travel_time: 97.0,
    route: 'Green',
    from_id: 'place-brkhl',
    to_id: 'place-bcnfd',
  },
  {
    service_date: '2025-02-25',
    travel_time: 98.0,
    route: 'Green',
    from_id: 'place-brkhl',
    to_id: 'place-bcnfd',
  },
  {
    service_date: '2025-02-24',
    travel_time: 96.0,
    route: 'Green',
    from_id: 'place-bvmnl',
    to_id: 'place-longw',
  },
  {
    service_date: '2025-02-25',
    travel_time: 92.0,
    route: 'Green',
    from_id: 'place-bvmnl',
    to_id: 'place-longw',
  },
  {
    service_date: '2025-02-24',
    travel_time: 87.0,
    route: 'Green',
    from_id: 'place-bvmnl',
    to_id: 'place-brkhl',
  },
  {
    service_date: '2025-02-25',
    travel_time: 89.0,
    route: 'Green',
    from_id: 'place-bvmnl',
    to_id: 'place-brkhl',
  },
  {
    service_date: '2025-02-24',
    travel_time: 66.0,
    route: 'Green',
    from_id: 'place-longw',
    to_id: 'place-fenwy',
  },
  {
    service_date: '2025-02-25',
    travel_time: 66.0,
    route: 'Green',
    from_id: 'place-longw',
    to_id: 'place-fenwy',
  },
  {
    service_date: '2025-02-24',
    travel_time: 83.0,
    route: 'Green',
    from_id: 'place-longw',
    to_id: 'place-bvmnl',
  },
  {
    service_date: '2025-02-25',
    travel_time: 84.0,
    route: 'Green',
    from_id: 'place-longw',
    to_id: 'place-bvmnl',
  },
  {
    service_date: '2025-02-24',
    travel_time: 159.5,
    route: 'Green',
    from_id: 'place-fenwy',
    to_id: 'place-kencl',
  },
  {
    service_date: '2025-02-25',
    travel_time: 159.5,
    route: 'Green',
    from_id: 'place-fenwy',
    to_id: 'place-kencl',
  },
  {
    service_date: '2025-02-24',
    travel_time: 67.0,
    route: 'Green',
    from_id: 'place-fenwy',
    to_id: 'place-longw',
  },
  {
    service_date: '2025-02-25',
    travel_time: 68.0,
    route: 'Green',
    from_id: 'place-fenwy',
    to_id: 'place-longw',
  },
  {
    service_date: '2025-02-24',
    travel_time: 55.0,
    route: 'Green',
    from_id: 'place-pktrm',
    to_id: 'place-boyls',
  },
  {
    service_date: '2025-02-25',
    travel_time: 60.0,
    route: 'Green',
    from_id: 'place-pktrm',
    to_id: 'place-boyls',
  },
  {
    service_date: '2025-02-24',
    travel_time: 76.0,
    route: 'Green',
    from_id: 'place-pktrm',
    to_id: 'place-gover',
  },
  {
    service_date: '2025-02-25',
    travel_time: 69.0,
    route: 'Green',
    from_id: 'place-pktrm',
    to_id: 'place-gover',
  },
  {
    service_date: '2025-02-24',
    travel_time: 100.0,
    route: 'Green',
    from_id: 'place-gover',
    to_id: 'place-haecl',
  },
  {
    service_date: '2025-02-25',
    travel_time: 101.0,
    route: 'Green',
    from_id: 'place-gover',
    to_id: 'place-haecl',
  },
  {
    service_date: '2025-02-24',
    travel_time: 86.0,
    route: 'Green',
    from_id: 'place-gover',
    to_id: 'place-pktrm',
  },
  {
    service_date: '2025-02-25',
    travel_time: 85.0,
    route: 'Green',
    from_id: 'place-gover',
    to_id: 'place-pktrm',
  },
  {
    service_date: '2025-02-24',
    travel_time: 68.0,
    route: 'Green',
    from_id: 'place-haecl',
    to_id: 'place-north',
  },
  {
    service_date: '2025-02-25',
    travel_time: 66.0,
    route: 'Green',
    from_id: 'place-haecl',
    to_id: 'place-north',
  },
  {
    service_date: '2025-02-24',
    travel_time: 82.0,
    route: 'Green',
    from_id: 'place-haecl',
    to_id: 'place-gover',
  },
  {
    service_date: '2025-02-25',
    travel_time: 86.0,
    route: 'Green',
    from_id: 'place-haecl',
    to_id: 'place-gover',
  },
  {
    service_date: '2025-02-24',
    travel_time: 151.5,
    route: 'Green',
    from_id: 'place-north',
    to_id: 'place-spmnl',
  },
  {
    service_date: '2025-02-25',
    travel_time: 153.0,
    route: 'Green',
    from_id: 'place-north',
    to_id: 'place-spmnl',
  },
  {
    service_date: '2025-02-24',
    travel_time: 50.0,
    route: 'Green',
    from_id: 'place-north',
    to_id: 'place-haecl',
  },
  {
    service_date: '2025-02-25',
    travel_time: 49.0,
    route: 'Green',
    from_id: 'place-north',
    to_id: 'place-haecl',
  },
  {
    service_date: '2025-02-24',
    travel_time: 74.0,
    route: 'Green',
    from_id: 'place-spmnl',
    to_id: 'place-lech',
  },
  {
    service_date: '2025-02-25',
    travel_time: 73.0,
    route: 'Green',
    from_id: 'place-spmnl',
    to_id: 'place-lech',
  },
  {
    service_date: '2025-02-24',
    travel_time: 148.0,
    route: 'Green',
    from_id: 'place-spmnl',
    to_id: 'place-north',
  },
  {
    service_date: '2025-02-25',
    travel_time: 148.0,
    route: 'Green',
    from_id: 'place-spmnl',
    to_id: 'place-north',
  },
  {
    service_date: '2025-02-24',
    travel_time: 61.0,
    route: 'Green',
    from_id: 'place-prmnl',
    to_id: 'place-symcl',
  },
  {
    service_date: '2025-02-25',
    travel_time: 61.0,
    route: 'Green',
    from_id: 'place-prmnl',
    to_id: 'place-symcl',
  },
  {
    service_date: '2025-02-24',
    travel_time: 50.0,
    route: 'Green',
    from_id: 'place-symcl',
    to_id: 'place-prmnl',
  },
  {
    service_date: '2025-02-25',
    travel_time: 50.0,
    route: 'Green',
    from_id: 'place-symcl',
    to_id: 'place-prmnl',
  },
  {
    service_date: '2025-02-24',
    travel_time: 316.0,
    route: 'Green',
    from_id: 'place-lech',
    to_id: 'place-unsqu',
  },
  {
    service_date: '2025-02-25',
    travel_time: 315.5,
    route: 'Green',
    from_id: 'place-lech',
    to_id: 'place-unsqu',
  },
  {
    service_date: '2025-02-24',
    travel_time: 79.0,
    route: 'Green',
    from_id: 'place-lech',
    to_id: 'place-spmnl',
  },
  {
    service_date: '2025-02-25',
    travel_time: 78.0,
    route: 'Green',
    from_id: 'place-lech',
    to_id: 'place-spmnl',
  },
  {
    service_date: '2025-02-24',
    travel_time: 67.0,
    route: 'Green',
    from_id: 'place-gilmn',
    to_id: 'place-mgngl',
  },
  {
    service_date: '2025-02-25',
    travel_time: 68.0,
    route: 'Green',
    from_id: 'place-gilmn',
    to_id: 'place-mgngl',
  },
  {
    service_date: '2025-02-24',
    travel_time: 84.0,
    route: 'Green',
    from_id: 'place-gilmn',
    to_id: 'place-esomr',
  },
  {
    service_date: '2025-02-25',
    travel_time: 87.0,
    route: 'Green',
    from_id: 'place-gilmn',
    to_id: 'place-esomr',
  },
  {
    service_date: '2025-02-24',
    travel_time: 54.0,
    route: 'Green',
    from_id: 'place-mgngl',
    to_id: 'place-balsq',
  },
  {
    service_date: '2025-02-25',
    travel_time: 55.0,
    route: 'Green',
    from_id: 'place-mgngl',
    to_id: 'place-balsq',
  },
  {
    service_date: '2025-02-24',
    travel_time: 67.0,
    route: 'Green',
    from_id: 'place-mgngl',
    to_id: 'place-gilmn',
  },
  {
    service_date: '2025-02-25',
    travel_time: 69.0,
    route: 'Green',
    from_id: 'place-mgngl',
    to_id: 'place-gilmn',
  },
  {
    service_date: '2025-02-24',
    travel_time: 108.0,
    route: 'Green',
    from_id: 'place-balsq',
    to_id: 'place-mdftf',
  },
  {
    service_date: '2025-02-25',
    travel_time: 120.0,
    route: 'Green',
    from_id: 'place-balsq',
    to_id: 'place-mdftf',
  },
  {
    service_date: '2025-02-24',
    travel_time: 53.0,
    route: 'Green',
    from_id: 'place-balsq',
    to_id: 'place-mgngl',
  },
  {
    service_date: '2025-02-25',
    travel_time: 54.0,
    route: 'Green',
    from_id: 'place-balsq',
    to_id: 'place-mgngl',
  },
  {
    service_date: '2025-02-24',
    travel_time: 94.5,
    route: 'Green',
    from_id: 'place-mdftf',
    to_id: 'place-balsq',
  },
  {
    service_date: '2025-02-25',
    travel_time: 96.0,
    route: 'Green',
    from_id: 'place-mdftf',
    to_id: 'place-balsq',
  },
  {
    service_date: '2025-02-24',
    travel_time: 79.0,
    route: 'Green',
    from_id: 'place-esomr',
    to_id: 'place-gilmn',
  },
  {
    service_date: '2025-02-25',
    travel_time: 82.0,
    route: 'Green',
    from_id: 'place-esomr',
    to_id: 'place-gilmn',
  },
  {
    service_date: '2025-02-24',
    travel_time: 70.0,
    route: 'Orange',
    from_id: 'place-forhl',
    to_id: 'place-grnst',
  },
  {
    service_date: '2025-02-25',
    travel_time: 71.0,
    route: 'Orange',
    from_id: 'place-forhl',
    to_id: 'place-grnst',
  },
  {
    service_date: '2025-02-24',
    travel_time: 119.0,
    route: 'Orange',
    from_id: 'place-grnst',
    to_id: 'place-forhl',
  },
  {
    service_date: '2025-02-25',
    travel_time: 128.5,
    route: 'Orange',
    from_id: 'place-grnst',
    to_id: 'place-forhl',
  },
  {
    service_date: '2025-02-24',
    travel_time: 78.0,
    route: 'Orange',
    from_id: 'place-grnst',
    to_id: 'place-sbmnl',
  },
  {
    service_date: '2025-02-25',
    travel_time: 79.0,
    route: 'Orange',
    from_id: 'place-grnst',
    to_id: 'place-sbmnl',
  },
  {
    service_date: '2025-02-24',
    travel_time: 46.0,
    route: 'Orange',
    from_id: 'place-sbmnl',
    to_id: 'place-grnst',
  },
  {
    service_date: '2025-02-25',
    travel_time: 47.0,
    route: 'Orange',
    from_id: 'place-sbmnl',
    to_id: 'place-grnst',
  },
  {
    service_date: '2025-02-24',
    travel_time: 79.0,
    route: 'Orange',
    from_id: 'place-sbmnl',
    to_id: 'place-jaksn',
  },
  {
    service_date: '2025-02-25',
    travel_time: 80.0,
    route: 'Orange',
    from_id: 'place-sbmnl',
    to_id: 'place-jaksn',
  },
  {
    service_date: '2025-02-24',
    travel_time: 54.0,
    route: 'Orange',
    from_id: 'place-jaksn',
    to_id: 'place-sbmnl',
  },
  {
    service_date: '2025-02-25',
    travel_time: 56.5,
    route: 'Orange',
    from_id: 'place-jaksn',
    to_id: 'place-sbmnl',
  },
  {
    service_date: '2025-02-24',
    travel_time: 50.0,
    route: 'Orange',
    from_id: 'place-jaksn',
    to_id: 'place-rcmnl',
  },
  {
    service_date: '2025-02-25',
    travel_time: 50.0,
    route: 'Orange',
    from_id: 'place-jaksn',
    to_id: 'place-rcmnl',
  },
  {
    service_date: '2025-02-24',
    travel_time: 52.0,
    route: 'Orange',
    from_id: 'place-rcmnl',
    to_id: 'place-jaksn',
  },
  {
    service_date: '2025-02-25',
    travel_time: 52.0,
    route: 'Orange',
    from_id: 'place-rcmnl',
    to_id: 'place-jaksn',
  },
  {
    service_date: '2025-02-24',
    travel_time: 45.0,
    route: 'Orange',
    from_id: 'place-rcmnl',
    to_id: 'place-rugg',
  },
  {
    service_date: '2025-02-25',
    travel_time: 45.0,
    route: 'Orange',
    from_id: 'place-rcmnl',
    to_id: 'place-rugg',
  },
  {
    service_date: '2025-02-24',
    travel_time: 46.0,
    route: 'Orange',
    from_id: 'place-rugg',
    to_id: 'place-rcmnl',
  },
  {
    service_date: '2025-02-25',
    travel_time: 46.0,
    route: 'Orange',
    from_id: 'place-rugg',
    to_id: 'place-rcmnl',
  },
  {
    service_date: '2025-02-24',
    travel_time: 43.0,
    route: 'Orange',
    from_id: 'place-rugg',
    to_id: 'place-masta',
  },
  {
    service_date: '2025-02-25',
    travel_time: 43.0,
    route: 'Orange',
    from_id: 'place-rugg',
    to_id: 'place-masta',
  },
  {
    service_date: '2025-02-24',
    travel_time: 38.0,
    route: 'Orange',
    from_id: 'place-masta',
    to_id: 'place-rugg',
  },
  {
    service_date: '2025-02-25',
    travel_time: 39.0,
    route: 'Orange',
    from_id: 'place-masta',
    to_id: 'place-rugg',
  },
  {
    service_date: '2025-02-24',
    travel_time: 78.0,
    route: 'Orange',
    from_id: 'place-masta',
    to_id: 'place-bbsta',
  },
  {
    service_date: '2025-02-25',
    travel_time: 78.0,
    route: 'Orange',
    from_id: 'place-masta',
    to_id: 'place-bbsta',
  },
  {
    service_date: '2025-02-24',
    travel_time: 80.0,
    route: 'Orange',
    from_id: 'place-bbsta',
    to_id: 'place-masta',
  },
  {
    service_date: '2025-02-25',
    travel_time: 80.0,
    route: 'Orange',
    from_id: 'place-bbsta',
    to_id: 'place-masta',
  },
  {
    service_date: '2025-02-24',
    travel_time: 72.0,
    route: 'Orange',
    from_id: 'place-bbsta',
    to_id: 'place-tumnl',
  },
  {
    service_date: '2025-02-25',
    travel_time: 72.0,
    route: 'Orange',
    from_id: 'place-bbsta',
    to_id: 'place-tumnl',
  },
  {
    service_date: '2025-02-24',
    travel_time: 100.0,
    route: 'Orange',
    from_id: 'place-tumnl',
    to_id: 'place-bbsta',
  },
  {
    service_date: '2025-02-25',
    travel_time: 100.0,
    route: 'Orange',
    from_id: 'place-tumnl',
    to_id: 'place-bbsta',
  },
  {
    service_date: '2025-02-24',
    travel_time: 28.0,
    route: 'Orange',
    from_id: 'place-tumnl',
    to_id: 'place-chncl',
  },
  {
    service_date: '2025-02-25',
    travel_time: 28.0,
    route: 'Orange',
    from_id: 'place-tumnl',
    to_id: 'place-chncl',
  },
  {
    service_date: '2025-02-24',
    travel_time: 25.0,
    route: 'Orange',
    from_id: 'place-chncl',
    to_id: 'place-tumnl',
  },
  {
    service_date: '2025-02-25',
    travel_time: 25.0,
    route: 'Orange',
    from_id: 'place-chncl',
    to_id: 'place-tumnl',
  },
  {
    service_date: '2025-02-24',
    travel_time: 28.0,
    route: 'Orange',
    from_id: 'place-chncl',
    to_id: 'place-dwnxg',
  },
  {
    service_date: '2025-02-25',
    travel_time: 28.0,
    route: 'Orange',
    from_id: 'place-chncl',
    to_id: 'place-dwnxg',
  },
  {
    service_date: '2025-02-24',
    travel_time: 28.0,
    route: 'Orange',
    from_id: 'place-dwnxg',
    to_id: 'place-chncl',
  },
  {
    service_date: '2025-02-25',
    travel_time: 28.0,
    route: 'Orange',
    from_id: 'place-dwnxg',
    to_id: 'place-chncl',
  },
  {
    service_date: '2025-02-24',
    travel_time: 24.0,
    route: 'Orange',
    from_id: 'place-dwnxg',
    to_id: 'place-state',
  },
  {
    service_date: '2025-02-25',
    travel_time: 25.0,
    route: 'Orange',
    from_id: 'place-dwnxg',
    to_id: 'place-state',
  },
  {
    service_date: '2025-02-24',
    travel_time: 14.0,
    route: 'Orange',
    from_id: 'place-state',
    to_id: 'place-dwnxg',
  },
  {
    service_date: '2025-02-25',
    travel_time: 14.0,
    route: 'Orange',
    from_id: 'place-state',
    to_id: 'place-dwnxg',
  },
  {
    service_date: '2025-02-24',
    travel_time: 20.0,
    route: 'Orange',
    from_id: 'place-state',
    to_id: 'place-haecl',
  },
  {
    service_date: '2025-02-25',
    travel_time: 20.0,
    route: 'Orange',
    from_id: 'place-state',
    to_id: 'place-haecl',
  },
  {
    service_date: '2025-02-24',
    travel_time: 42.0,
    route: 'Orange',
    from_id: 'place-haecl',
    to_id: 'place-state',
  },
  {
    service_date: '2025-02-25',
    travel_time: 42.0,
    route: 'Orange',
    from_id: 'place-haecl',
    to_id: 'place-state',
  },
  {
    service_date: '2025-02-24',
    travel_time: 30.0,
    route: 'Orange',
    from_id: 'place-haecl',
    to_id: 'place-north',
  },
  {
    service_date: '2025-02-25',
    travel_time: 30.0,
    route: 'Orange',
    from_id: 'place-haecl',
    to_id: 'place-north',
  },
  {
    service_date: '2025-02-24',
    travel_time: 32.5,
    route: 'Orange',
    from_id: 'place-north',
    to_id: 'place-haecl',
  },
  {
    service_date: '2025-02-25',
    travel_time: 32.0,
    route: 'Orange',
    from_id: 'place-north',
    to_id: 'place-haecl',
  },
  {
    service_date: '2025-02-24',
    travel_time: 86.0,
    route: 'Orange',
    from_id: 'place-north',
    to_id: 'place-ccmnl',
  },
  {
    service_date: '2025-02-25',
    travel_time: 86.0,
    route: 'Orange',
    from_id: 'place-north',
    to_id: 'place-ccmnl',
  },
  {
    service_date: '2025-02-24',
    travel_time: 89.0,
    route: 'Orange',
    from_id: 'place-ccmnl',
    to_id: 'place-north',
  },
  {
    service_date: '2025-02-25',
    travel_time: 90.0,
    route: 'Orange',
    from_id: 'place-ccmnl',
    to_id: 'place-north',
  },
  {
    service_date: '2025-02-24',
    travel_time: 75.0,
    route: 'Orange',
    from_id: 'place-ccmnl',
    to_id: 'place-sull',
  },
  {
    service_date: '2025-02-25',
    travel_time: 75.0,
    route: 'Orange',
    from_id: 'place-ccmnl',
    to_id: 'place-sull',
  },
  {
    service_date: '2025-02-24',
    travel_time: 78.0,
    route: 'Orange',
    from_id: 'place-sull',
    to_id: 'place-ccmnl',
  },
  {
    service_date: '2025-02-25',
    travel_time: 78.0,
    route: 'Orange',
    from_id: 'place-sull',
    to_id: 'place-ccmnl',
  },
  {
    service_date: '2025-02-24',
    travel_time: 49.0,
    route: 'Orange',
    from_id: 'place-sull',
    to_id: 'place-astao',
  },
  {
    service_date: '2025-02-25',
    travel_time: 49.0,
    route: 'Orange',
    from_id: 'place-sull',
    to_id: 'place-astao',
  },
  {
    service_date: '2025-02-24',
    travel_time: 53.0,
    route: 'Orange',
    from_id: 'place-welln',
    to_id: 'place-astao',
  },
  {
    service_date: '2025-02-25',
    travel_time: 53.0,
    route: 'Orange',
    from_id: 'place-welln',
    to_id: 'place-astao',
  },
  {
    service_date: '2025-02-24',
    travel_time: 163.0,
    route: 'Orange',
    from_id: 'place-welln',
    to_id: 'place-mlmnl',
  },
  {
    service_date: '2025-02-25',
    travel_time: 184.0,
    route: 'Orange',
    from_id: 'place-welln',
    to_id: 'place-mlmnl',
  },
  {
    service_date: '2025-02-24',
    travel_time: 160.0,
    route: 'Orange',
    from_id: 'place-mlmnl',
    to_id: 'place-welln',
  },
  {
    service_date: '2025-02-25',
    travel_time: 170.0,
    route: 'Orange',
    from_id: 'place-mlmnl',
    to_id: 'place-welln',
  },
  {
    service_date: '2025-02-24',
    travel_time: 187.0,
    route: 'Orange',
    from_id: 'place-mlmnl',
    to_id: 'place-ogmnl',
  },
  {
    service_date: '2025-02-25',
    travel_time: 174.5,
    route: 'Orange',
    from_id: 'place-mlmnl',
    to_id: 'place-ogmnl',
  },
  {
    service_date: '2025-02-24',
    travel_time: 69.0,
    route: 'Orange',
    from_id: 'place-ogmnl',
    to_id: 'place-mlmnl',
  },
  {
    service_date: '2025-02-25',
    travel_time: 73.0,
    route: 'Orange',
    from_id: 'place-ogmnl',
    to_id: 'place-mlmnl',
  },
  {
    service_date: '2025-02-24',
    travel_time: 48.0,
    route: 'Orange',
    from_id: 'place-astao',
    to_id: 'place-sull',
  },
  {
    service_date: '2025-02-25',
    travel_time: 48.0,
    route: 'Orange',
    from_id: 'place-astao',
    to_id: 'place-sull',
  },
  {
    service_date: '2025-02-24',
    travel_time: 56.0,
    route: 'Orange',
    from_id: 'place-astao',
    to_id: 'place-welln',
  },
  {
    service_date: '2025-02-25',
    travel_time: 56.0,
    route: 'Orange',
    from_id: 'place-astao',
    to_id: 'place-welln',
  },
  {
    service_date: '2025-02-24',
    travel_time: 93.0,
    route: 'Red',
    from_id: 'place-alfcl',
    to_id: 'place-davis',
  },
  {
    service_date: '2025-02-25',
    travel_time: 100.5,
    route: 'Red',
    from_id: 'place-alfcl',
    to_id: 'place-davis',
  },
  {
    service_date: '2025-02-24',
    travel_time: 83.0,
    route: 'Red',
    from_id: 'place-davis',
    to_id: 'place-portr',
  },
  {
    service_date: '2025-02-25',
    travel_time: 83.0,
    route: 'Red',
    from_id: 'place-davis',
    to_id: 'place-portr',
  },
  {
    service_date: '2025-02-24',
    travel_time: 203.0,
    route: 'Red',
    from_id: 'place-davis',
    to_id: 'place-alfcl',
  },
  {
    service_date: '2025-02-25',
    travel_time: 238.0,
    route: 'Red',
    from_id: 'place-davis',
    to_id: 'place-alfcl',
  },
  {
    service_date: '2025-02-24',
    travel_time: 104.0,
    route: 'Red',
    from_id: 'place-portr',
    to_id: 'place-harsq',
  },
  {
    service_date: '2025-02-25',
    travel_time: 103.0,
    route: 'Red',
    from_id: 'place-portr',
    to_id: 'place-harsq',
  },
  {
    service_date: '2025-02-24',
    travel_time: 104.0,
    route: 'Red',
    from_id: 'place-portr',
    to_id: 'place-davis',
  },
  {
    service_date: '2025-02-25',
    travel_time: 103.5,
    route: 'Red',
    from_id: 'place-portr',
    to_id: 'place-davis',
  },
  {
    service_date: '2025-02-24',
    travel_time: 152.0,
    route: 'Red',
    from_id: 'place-harsq',
    to_id: 'place-cntsq',
  },
  {
    service_date: '2025-02-25',
    travel_time: 154.0,
    route: 'Red',
    from_id: 'place-harsq',
    to_id: 'place-cntsq',
  },
  {
    service_date: '2025-02-24',
    travel_time: 116.0,
    route: 'Red',
    from_id: 'place-harsq',
    to_id: 'place-portr',
  },
  {
    service_date: '2025-02-25',
    travel_time: 117.0,
    route: 'Red',
    from_id: 'place-harsq',
    to_id: 'place-portr',
  },
  {
    service_date: '2025-02-24',
    travel_time: 82.0,
    route: 'Red',
    from_id: 'place-cntsq',
    to_id: 'place-knncl',
  },
  {
    service_date: '2025-02-25',
    travel_time: 82.0,
    route: 'Red',
    from_id: 'place-cntsq',
    to_id: 'place-knncl',
  },
  {
    service_date: '2025-02-24',
    travel_time: 154.0,
    route: 'Red',
    from_id: 'place-cntsq',
    to_id: 'place-harsq',
  },
  {
    service_date: '2025-02-25',
    travel_time: 152.0,
    route: 'Red',
    from_id: 'place-cntsq',
    to_id: 'place-harsq',
  },
  {
    service_date: '2025-02-24',
    travel_time: 69.0,
    route: 'Red',
    from_id: 'place-knncl',
    to_id: 'place-chmnl',
  },
  {
    service_date: '2025-02-25',
    travel_time: 69.0,
    route: 'Red',
    from_id: 'place-knncl',
    to_id: 'place-chmnl',
  },
  {
    service_date: '2025-02-24',
    travel_time: 65.0,
    route: 'Red',
    from_id: 'place-knncl',
    to_id: 'place-cntsq',
  },
  {
    service_date: '2025-02-25',
    travel_time: 65.0,
    route: 'Red',
    from_id: 'place-knncl',
    to_id: 'place-cntsq',
  },
  {
    service_date: '2025-02-24',
    travel_time: 61.0,
    route: 'Red',
    from_id: 'place-chmnl',
    to_id: 'place-pktrm',
  },
  {
    service_date: '2025-02-25',
    travel_time: 63.0,
    route: 'Red',
    from_id: 'place-chmnl',
    to_id: 'place-pktrm',
  },
  {
    service_date: '2025-02-24',
    travel_time: 46.0,
    route: 'Red',
    from_id: 'place-chmnl',
    to_id: 'place-knncl',
  },
  {
    service_date: '2025-02-25',
    travel_time: 46.0,
    route: 'Red',
    from_id: 'place-chmnl',
    to_id: 'place-knncl',
  },
  {
    service_date: '2025-02-24',
    travel_time: 22.0,
    route: 'Red',
    from_id: 'place-pktrm',
    to_id: 'place-dwnxg',
  },
  {
    service_date: '2025-02-25',
    travel_time: 22.0,
    route: 'Red',
    from_id: 'place-pktrm',
    to_id: 'place-dwnxg',
  },
  {
    service_date: '2025-02-24',
    travel_time: 61.0,
    route: 'Red',
    from_id: 'place-pktrm',
    to_id: 'place-chmnl',
  },
  {
    service_date: '2025-02-25',
    travel_time: 61.0,
    route: 'Red',
    from_id: 'place-pktrm',
    to_id: 'place-chmnl',
  },
  {
    service_date: '2025-02-24',
    travel_time: 25.0,
    route: 'Red',
    from_id: 'place-dwnxg',
    to_id: 'place-sstat',
  },
  {
    service_date: '2025-02-25',
    travel_time: 25.0,
    route: 'Red',
    from_id: 'place-dwnxg',
    to_id: 'place-sstat',
  },
  {
    service_date: '2025-02-24',
    travel_time: 17.0,
    route: 'Red',
    from_id: 'place-dwnxg',
    to_id: 'place-pktrm',
  },
  {
    service_date: '2025-02-25',
    travel_time: 17.0,
    route: 'Red',
    from_id: 'place-dwnxg',
    to_id: 'place-pktrm',
  },
  {
    service_date: '2025-02-24',
    travel_time: 130.0,
    route: 'Red',
    from_id: 'place-sstat',
    to_id: 'place-brdwy',
  },
  {
    service_date: '2025-02-25',
    travel_time: 134.0,
    route: 'Red',
    from_id: 'place-sstat',
    to_id: 'place-brdwy',
  },
  {
    service_date: '2025-02-24',
    travel_time: 23.0,
    route: 'Red',
    from_id: 'place-sstat',
    to_id: 'place-dwnxg',
  },
  {
    service_date: '2025-02-25',
    travel_time: 23.0,
    route: 'Red',
    from_id: 'place-sstat',
    to_id: 'place-dwnxg',
  },
  {
    service_date: '2025-02-24',
    travel_time: 114.0,
    route: 'Red',
    from_id: 'place-brdwy',
    to_id: 'place-andrw',
  },
  {
    service_date: '2025-02-25',
    travel_time: 117.0,
    route: 'Red',
    from_id: 'place-brdwy',
    to_id: 'place-andrw',
  },
  {
    service_date: '2025-02-24',
    travel_time: 94.0,
    route: 'Red',
    from_id: 'place-brdwy',
    to_id: 'place-sstat',
  },
  {
    service_date: '2025-02-25',
    travel_time: 93.0,
    route: 'Red',
    from_id: 'place-brdwy',
    to_id: 'place-sstat',
  },
  {
    service_date: '2025-02-24',
    travel_time: 100.0,
    route: 'Red',
    from_id: 'place-andrw',
    to_id: 'place-jfk',
  },
  {
    service_date: '2025-02-25',
    travel_time: 102.0,
    route: 'Red',
    from_id: 'place-andrw',
    to_id: 'place-jfk',
  },
  {
    service_date: '2025-02-24',
    travel_time: 102.5,
    route: 'Red',
    from_id: 'place-andrw',
    to_id: 'place-jfk',
  },
  {
    service_date: '2025-02-25',
    travel_time: 102.0,
    route: 'Red',
    from_id: 'place-andrw',
    to_id: 'place-jfk',
  },
  {
    service_date: '2025-02-24',
    travel_time: 113.0,
    route: 'Red',
    from_id: 'place-andrw',
    to_id: 'place-brdwy',
  },
  {
    service_date: '2025-02-25',
    travel_time: 115.0,
    route: 'Red',
    from_id: 'place-andrw',
    to_id: 'place-brdwy',
  },
  {
    service_date: '2025-02-24',
    travel_time: 147.0,
    route: 'Red',
    from_id: 'place-jfk',
    to_id: 'place-shmnl',
  },
  {
    service_date: '2025-02-25',
    travel_time: 146.0,
    route: 'Red',
    from_id: 'place-jfk',
    to_id: 'place-shmnl',
  },
  {
    service_date: '2025-02-24',
    travel_time: 102.0,
    route: 'Red',
    from_id: 'place-jfk',
    to_id: 'place-andrw',
  },
  {
    service_date: '2025-02-25',
    travel_time: 101.5,
    route: 'Red',
    from_id: 'place-jfk',
    to_id: 'place-andrw',
  },
  {
    service_date: '2025-02-24',
    travel_time: 130.0,
    route: 'Red',
    from_id: 'place-shmnl',
    to_id: 'place-fldcr',
  },
  {
    service_date: '2025-02-25',
    travel_time: 131.0,
    route: 'Red',
    from_id: 'place-shmnl',
    to_id: 'place-fldcr',
  },
  {
    service_date: '2025-02-24',
    travel_time: 67.0,
    route: 'Red',
    from_id: 'place-shmnl',
    to_id: 'place-jfk',
  },
  {
    service_date: '2025-02-25',
    travel_time: 67.0,
    route: 'Red',
    from_id: 'place-shmnl',
    to_id: 'place-jfk',
  },
  {
    service_date: '2025-02-24',
    travel_time: 54.0,
    route: 'Red',
    from_id: 'place-fldcr',
    to_id: 'place-smmnl',
  },
  {
    service_date: '2025-02-25',
    travel_time: 55.0,
    route: 'Red',
    from_id: 'place-fldcr',
    to_id: 'place-smmnl',
  },
  {
    service_date: '2025-02-24',
    travel_time: 148.0,
    route: 'Red',
    from_id: 'place-fldcr',
    to_id: 'place-shmnl',
  },
  {
    service_date: '2025-02-25',
    travel_time: 148.0,
    route: 'Red',
    from_id: 'place-fldcr',
    to_id: 'place-shmnl',
  },
  {
    service_date: '2025-02-24',
    travel_time: 99.0,
    route: 'Red',
    from_id: 'place-smmnl',
    to_id: 'place-asmnl',
  },
  {
    service_date: '2025-02-25',
    travel_time: 99.0,
    route: 'Red',
    from_id: 'place-smmnl',
    to_id: 'place-asmnl',
  },
  {
    service_date: '2025-02-24',
    travel_time: 48.0,
    route: 'Red',
    from_id: 'place-smmnl',
    to_id: 'place-fldcr',
  },
  {
    service_date: '2025-02-25',
    travel_time: 47.0,
    route: 'Red',
    from_id: 'place-smmnl',
    to_id: 'place-fldcr',
  },
  {
    service_date: '2025-02-24',
    travel_time: 58.0,
    route: 'Red',
    from_id: 'place-asmnl',
    to_id: 'place-smmnl',
  },
  {
    service_date: '2025-02-25',
    travel_time: 56.0,
    route: 'Red',
    from_id: 'place-asmnl',
    to_id: 'place-smmnl',
  },
  {
    service_date: '2025-02-24',
    travel_time: 330.5,
    route: 'Red',
    from_id: 'place-jfk',
    to_id: 'place-nqncy',
  },
  {
    service_date: '2025-02-25',
    travel_time: 330.0,
    route: 'Red',
    from_id: 'place-jfk',
    to_id: 'place-nqncy',
  },
  {
    service_date: '2025-02-24',
    travel_time: 104.0,
    route: 'Red',
    from_id: 'place-jfk',
    to_id: 'place-andrw',
  },
  {
    service_date: '2025-02-25',
    travel_time: 104.0,
    route: 'Red',
    from_id: 'place-jfk',
    to_id: 'place-andrw',
  },
  {
    service_date: '2025-02-24',
    travel_time: 68.0,
    route: 'Red',
    from_id: 'place-nqncy',
    to_id: 'place-wlsta',
  },
  {
    service_date: '2025-02-25',
    travel_time: 67.0,
    route: 'Red',
    from_id: 'place-nqncy',
    to_id: 'place-wlsta',
  },
  {
    service_date: '2025-02-24',
    travel_time: 330.0,
    route: 'Red',
    from_id: 'place-nqncy',
    to_id: 'place-jfk',
  },
  {
    service_date: '2025-02-25',
    travel_time: 328.0,
    route: 'Red',
    from_id: 'place-nqncy',
    to_id: 'place-jfk',
  },
  {
    service_date: '2025-02-24',
    travel_time: 133.5,
    route: 'Red',
    from_id: 'place-wlsta',
    to_id: 'place-qnctr',
  },
  {
    service_date: '2025-02-25',
    travel_time: 137.0,
    route: 'Red',
    from_id: 'place-wlsta',
    to_id: 'place-qnctr',
  },
  {
    service_date: '2025-02-24',
    travel_time: 72.0,
    route: 'Red',
    from_id: 'place-wlsta',
    to_id: 'place-nqncy',
  },
  {
    service_date: '2025-02-25',
    travel_time: 72.0,
    route: 'Red',
    from_id: 'place-wlsta',
    to_id: 'place-nqncy',
  },
  {
    service_date: '2025-02-24',
    travel_time: 123.0,
    route: 'Red',
    from_id: 'place-qnctr',
    to_id: 'place-qamnl',
  },
  {
    service_date: '2025-02-25',
    travel_time: 122.0,
    route: 'Red',
    from_id: 'place-qnctr',
    to_id: 'place-qamnl',
  },
  {
    service_date: '2025-02-24',
    travel_time: 154.0,
    route: 'Red',
    from_id: 'place-qnctr',
    to_id: 'place-wlsta',
  },
  {
    service_date: '2025-02-25',
    travel_time: 155.0,
    route: 'Red',
    from_id: 'place-qnctr',
    to_id: 'place-wlsta',
  },
  {
    service_date: '2025-02-24',
    travel_time: 248.5,
    route: 'Red',
    from_id: 'place-qamnl',
    to_id: 'place-brntn',
  },
  {
    service_date: '2025-02-25',
    travel_time: 252.0,
    route: 'Red',
    from_id: 'place-qamnl',
    to_id: 'place-brntn',
  },
  {
    service_date: '2025-02-24',
    travel_time: 124.0,
    route: 'Red',
    from_id: 'place-qamnl',
    to_id: 'place-qnctr',
  },
  {
    service_date: '2025-02-25',
    travel_time: 123.0,
    route: 'Red',
    from_id: 'place-qamnl',
    to_id: 'place-qnctr',
  },
  {
    service_date: '2025-02-24',
    travel_time: 186.0,
    route: 'Red',
    from_id: 'place-brntn',
    to_id: 'place-qamnl',
  },
  {
    service_date: '2025-02-25',
    travel_time: 184.0,
    route: 'Red',
    from_id: 'place-brntn',
    to_id: 'place-qamnl',
  },
];
