export default {
  "Englewood Avenue": "Englewood",
  Braintree: "Braintree",
  "Saint Paul Street (C)": "St Paul",
  Waban: "Waban",
  Wellington: "Wellington",
  Haymarket: "Haymkt",
  "Brandon Hall": "Brandon",
  Hynes: "Hynes",
  "Washington Square": "Wash Sq",
  "Newton Centre": "Newton Ctr",
  Lechmere: "Lechmere",
  "Kent Street": "Kent",
  "Green Street": "Green",
  Reservoir: "Reservoir",
  "Revere Beach": "Revere",
  Longwood: "Longwood",
  Eliot: "Eliot",
  "Boston College": "BC",
  "Fairbanks Street": "Fairbanks",
  Ruggles: "Ruggles",
  Andrew: "Andrew",
  Woodland: "Woodland",
  Porter: "Porter",
  Riverside: "Riverside",
  Symphony: "Symphony",
  "Saint Marys Street": "St Marys",
  Arlington: "Arlington",
  "Kendall/MIT": "MIT",
  "Park Street": "Park",
  "Science Park": "Science",
  Shawmut: "Shawmut",
  "Summit Avenue": "Summit",
  "Savin Hill": "Savin H",
  "Brookline Village": "Brookline Vlg",
  Prudential: "Pru",
  "Newton Highlands": "Newton Hlands",
  "Government Center": "Govt Ctr",
  "Back Bay": "BBY",
  "Coolidge Corner": "Coolidge",
  "Saint Paul Street (B)": "St Paul",
  "Jackson Square": "Jackson Sq",
  Alewife: "Alewife",
  Maverick: "Maverick",
  Airport: "Airport",
  "Heath Street": "Heath",
  "Cleveland Circle": "Cleveland Cir",
  "JFK/UMass (Ashmont)": "JFK (A)",
  "Back of the Hill": "BotH",
  Fenway: "Fenway",
  "Sutherland Road": "Sutherland",
  Ashmont: "Ashmont",
  "Boston University West": "BU West",
  "Allston Street": "Allston St",
  "Washington Street": "Wash. St",
  Aquarium: "Aquarium",
  "Fields Corner": "Fields Corner",
  Bowdoin: "Bowdoin",
  "Northeastern University": "NEU",
  "Chestnut Hill": "Chestnut Hill",
  "Hawes Street": "Hawes",
  "Chestnut Hill Avenue": "Chestnut Hill Ave",
  "Tufts Medical Center": "Tufts Med Ctr",
  "Stony Brook": "Stony Brook",
  "Griggs Street": "Griggs",
  "Warren Street": "Warren",
  "Chiswick Road": "Chiswick",
  "North Quincy": "N Quincy",
  "Museum of Fine Arts": "MFA",
  "Harvard Avenue": "Harvard Ave",
  Kenmore: "Kenmore",
  "Dean Road": "Dean",
  Chinatown: "Chinatown",
  Copley: "Copley",
  "Roxbury Crossing": "Rox Xing",
  "Orient Heights": "Orient H",
  "Quincy Adams": "Quincy Adams",
  "Blandford Street": "Blandford",
  Boylston: "Boylston",
  "Massachusetts Avenue": "Mass Ave",
  "Malden Center": "Malden",
  "Charles/MGH": "MGH",
  "South Street": "South St",
  "Sullivan Square": "Sullivan Sq",
  "Brookline Hills": "Brookline Hills",
  "Forest Hills": "Forest Hills",
  "Mission Park": "Mission Pk",
  "Suffolk Downs": "Suffolk Downs",
  "Fenwood Road": "Fenwood",
  "Babcock Street": "Babcock",
  Broadway: "Broadway",
  "Brigham Circle": "Brigham",
  "South Station": "SS",
  Beaconsfield: "Beaconsfield",
  "Community College": "Comm College",
  Beachmont: "Beachmont",
  "Wood Island": "Wood Isl",
  "Downtown Crossing": "DTX",
  "Boston University East": "BU East",
  Central: "Central",
  "Pleasant Street": "Pleasant",
  "Tappan Street": "Tappan",
  Riverway: "Riverway",
  "Boston University Central": "BU Central",
  Wonderland: "Wonderland",
  "Quincy Center": "Quincy Ctr",
  Assembly: "Assembly",
  "JFK/UMass (Braintree)": "JFK (B)",
  "State Street": "State",
  Davis: "Davis",
  "Longwood Medical Area": "LMA",
  Harvard: "Harvard",
  "North Station": "North Station",
  "Packards Corner": "Packards",
  "Oak Grove": "Oak Grove",
};
